ndphillips/FFTrees

R/FFForest.R
R/FFTrees.R
R/growFFTrees_function.R
R/plotFFTrees_function.R
R/predictFFTrees_function.R
README.md
man/FFForest.Rd
man/FFTrees.Rd
man/grow.FFTrees.Rd
man/plot.FFTrees.Rd
man/predict.FFTrees.Rd

Hi, while reading the code for FFTrees I noticed that the work "deprecated" was misspelled as "depricated" I corrected the spelling. 
Thanks

Corrected spelling of depricated to deprecated

---

NEWS.md
R/plotFFTrees_function.R
tests/testthat/test-plotFFTrees_function.R

Related to #47 
* Graphic params are reset, not changed..  
* Deprecation noticed are now reported as warnings.
* `print()` --> `message()` for best tree

47 cran comments

---

cran-comments.md
vignettes/apa.csl

Preparing for CRAN resubmission:
* Changed automated references from "http://doi.org/" to "https://doi.org/" (to fix invalid URLs).

Fix CRAN issue

---

DESCRIPTION
NEWS.md
R/fftrees_fitcomp.R
R/fftrees_grow_fan.R
R/helper.R
README.Rmd
README.md
man/classtable.Rd
man/comp_pred.Rd

This set of commits computes and provides `wacc` for all competing algorithms (by passing current `sens.w` value from `fftrees_fitcomp()` to `comp_pred()` and from there to `classtable()` (which now uses a default of `sens.w = NULL` to enforce that current value is being passed from all calling functions).

Compute `wacc` for and include in stats of competing algorithms

---

DESCRIPTION
NEWS.md
R/plotFFTrees_function.R
R/printFFTrees_function.R
README.md
man/plot.FFTrees.Rd
man/print.FFTrees.Rd

This PR addresses the bug of Issue #91 — i.e., re-enables plotting and printing trees when providing a data frame as `data` for both `print()` and `plot()` — but does not (yet) use a `newdata` argument.

Using data for providing new `data` (as df) in `print()` or `plot()`

---

DESCRIPTION
NEWS.md
R/plotFFTrees_function.R
R/printFFTrees_function.R
README.md
man/plot.FFTrees.Rd
man/print.FFTrees.Rd

Returning a possibly modified `FFTrees` object `x` allows to re-assign it to a global `x` when it has been changed within either function by applying `x` to new test data (provided as df to the `data` argument).

Return invisible `FFTrees` object `x` when plotting or printing `x`

---

R/helper_plot.R
R/plotFFTrees_function.R
man/plot.FFTrees.Rd

Improve efficiency:  When calling `add_level()` from `plot.FFTrees()`, pass only the relevant row of data frame `lloc`, rather than the entire df for very level.

Increase efficiency of `add_level()` helper

---

DESCRIPTION
NEWS.md
R/fftrees_apply.R
R/fftrees_grow_fan.R
R/helper.R
README.md
man/fftrees_grow_fan.Rd
man/select_best_tree.Rd

As the **dprime** values of trees were not recorded in tree stats, it was not possible to set `goal = "dprime"` in `FFTrees()` (i.e., select FFTs by their dprime value). 
The current PR fixes this — and hopefully works without causing new issues, as it doesn't affect any fundamental moving parts.
However, allowing to use **dprime** as `goal.chase` or `goal.threshold` will require more profound changes, and should probably be supported by _reporting_ both current **goals** and **dprime** values when printing and plotting FFTs.

Allowing to select FFTs by dprime value (i.e., `goal = 'dprime'`)

---

DESCRIPTION
R/fftrees_cuerank.R
R/fftrees_grow_fan.R
README.Rmd
README.md
man/fftrees_cuerank.Rd
man/fftrees_grow_fan.Rd

Minor maintenance changes:
- Added and unified variables for stats computed in `fftrees_grow_fan()`. 
- Renamed some variables to distinguish internal variables (using `_`) from function arguments (using `.`).
- Updated documentation.
The background of these changes are discussed in Issue #93.  However, actually using new variables (e.g., dprime) in `goal.chase` or `goal.threshold` would additionally require adding them to cue statistics in `x$cues$stats$train`.

Maintenance: Stats computed when growing FFTs

---

DESCRIPTION
NEWS.md
R/fftrees_apply.R
README.Rmd
README.md

Trimming both leading and trailing spaces when interpreting tree definitions (in `fftrees_apply()`, to address Issue #111).

Trim spaces in tree definitions

---

DESCRIPTION
NEWS.md
R/FFTrees.R
R/fftrees_apply.R
R/fftrees_define.R
R/fftrees_fitcomp.R
R/fftrees_grow_fan.R
R/fftrees_wordstofftrees.R
R/helper.R
README.Rmd
README.md
man/FFTrees.Rd
man/fftrees_define.Rd
vignettes/FFTrees_function.Rmd
vignettes/FFTrees_mytree.Rmd

This PR still addresses Issue #111 and serves 2 functions:
1. **Manually defining FFTs**:  In `FFTrees()`, both providing `tree.definitions` (as a `data.frame`) and an `object` (as an `FFTrees` object) allow providing existing FFT definitions.  To manage their interaction, both arguments are now passed on to `fftrees_define()`.  If either argument is present, its FFTs are used as the tree definitions of `x$trees$definitions`. If _both_ are present, `tree.definitions` take priority over `object`.
2. Provide more consistent and explicit **user feedback** on current steps and progress:  Most key steps now provide 2 messages: An initial "aiming to ..." and a final "successfully done" message. This allows pin-pointing errors more precisely (and can be suppressed by `quiet = TRUE`).

Manually defining FFTs and user feedback

---

DESCRIPTION
R/FFTrees.R
R/fftrees_apply.R
R/fftrees_create.R
R/fftrees_cuerank.R
R/fftrees_define.R
R/fftrees_fitcomp.R
R/fftrees_grow_fan.R
R/fftrees_wordstofftrees.R
R/helper.R
R/predictFFTrees_function.R
README.Rmd
README.md
man/FFTrees.Rd
man/fftrees_create.Rd
vignettes/FFTrees_examples.Rmd
vignettes/FFTrees_function.Rmd
vignettes/FFTrees_heart.Rmd
vignettes/FFTrees_mytree.Rmd
vignettes/FFTrees_plot.Rmd
vignettes/guide.Rmd

Provide more explicit and more diagnostic user feedback (using **crayon** styles).
Also, when `FFTrees()` is provided with a valid `object`, its current values are used for missing values of `formula` and `data` to facilitate manual definitions of FFTs.

Improve and unify user feedback

---

DESCRIPTION
R/fftrees_apply.R
R/fftrees_cuerank.R
README.Rmd
README.md
vignettes/FFTrees_heart.Rmd
vignettes/FFTrees_mytree.Rmd

Revised the vignette on **Manually defining FFTs** by including an example that modifies and evaluates a set of `tree.definitions` (to explain changes in response to Issue #111).

Manually defining FFTs

---

DESCRIPTION
NEWS.md
R/helper.R
R/helper_col.R
R/helper_plot.R
R/printFFTrees_function.R
R/summaryFFTrees_function.R
R/zzz.R
README.Rmd
README.md

As the **crayon** package is being superseded by the **cli** package, this PR replaces corresponding function calls:
Colored terminal output (e.g., in summaries and user feedback messages) is now handled by ANSI styles (defined in `helper_col.R`).

Replace **crayon** by **cli** functions

---

DESCRIPTION
NEWS.md
R/fftrees_cuerank.R
R/fftrees_threshold_factor_grid.R
R/fftrees_threshold_numeric_grid.R
R/helper.R
man/add_stats.Rd
man/classtable.Rd

This PR mostly enables optimizing for `dprime` (as `goal.threshold`, `goal.chase`, and `goal`).  Changes include: 
- computing `dprime` values in `add_stats()` helper (with `correction`)
- include `dprime` values in cue level statistics (in `x$cues$thresholds` and `x$cues$stats`)
- minor cleanups in `fftrees_cuerank()`, `fftrees_threshold_factor_grid()` and `fftrees_threshold_numeric_grid()` 
This mostly resolves Issue #93, but the new functionality is not thoroughly tested yet.  Initial tests suggest that optimizing for `dprime` can substantially lower other accuracy measures.

Enabling optimizing FFTs for `dprime`

---

DESCRIPTION
NEWS.md
R/FFTrees.R
R/fftrees_apply.R
R/fftrees_create.R
R/fftrees_cuerank.R
R/fftrees_grow_fan.R
R/fftrees_threshold_factor_grid.R
R/fftrees_threshold_numeric_grid.R
R/helper_stats.R
README.Rmd
README.md
man/FFTrees.Rd
man/add_stats.Rd
man/classtable.Rd
man/fftrees_create.Rd
man/fftrees_threshold_factor_grid.Rd
man/fftrees_threshold_numeric_grid.Rd

This PR enables setting a user-defined goal (`my.goal`, as defined by `my.goal.fun`) and — if defined — computes the corresponding measure and reports it in both cue level and tree level statistics. 
Note that the status of the `my.goal` measure is currently **experimental**: 
- the values are only _computed_ and _reported_ (as a dependent variable), but, not yet _used_ as a criterion _for optimization_ purposes (in goals)
- the 2 new arguments are currently defined and set by `fftrees_create()`, but not yet by main `FFTrees()` function

Enable a user-defined goal measure

---

DESCRIPTION
NEWS.md
R/fftrees_apply.R
R/fftrees_create.R
R/fftrees_grow_fan.R
R/fftrees_ranktrees.R
R/fftrees_threshold_factor_grid.R
R/helper.R
R/plotFFTrees_function.R
R/printFFTrees_function.R
README.Rmd
README.md
man/select_best_tree.Rd

This PR enables **optimization** for a user-defined `my.goal` (as defined by `my.goal.fun`) on both cue level (`goal.threshold`) and tree level (`goal.chase` and `goal`).  However, this functionality is still **explorative** (i.e., set in `fftrees_create()`, rather than enabled for main `FFTrees()` function).
Some additional code cleanup and maintenance (to improve consistency and performance).

Enabling user-defined goal & general maintenance

---

DESCRIPTION
NEWS.md
R/fftrees_apply.R
R/fftrees_grow_fan.R
R/fftrees_wordstofftrees.R
R/summaryFFTrees_function.R
R/util_gfft.R
README.Rmd
README.md
tests/testthat/test-mytree.R

This PR improves the package's **consistency**, **modularity**, and **robustness**, by completing the overhaul of tree translation functions and code snippets of the last 2 PRs.  Details include:
- using complementary `read_fft_df()` and `write_fft_df()` functions (and corresponding verification functions)
- using a global tree node separator `fft_node_sep` (also in tests)
- providing more consistent and explicit user feedback
- providing more informative `summary()` (e.g., on params)
**Please note**:  Due to the wide range of changes and despite careful checks, the OLD code snippets are currently only commented out (in case something should break).  If all goes well, they will be removed in future cleanups...

Completing overhaul of FFT translation functions (plus many minor changes)

---

DESCRIPTION
NEWS.md
R/fftrees_wordstofftrees.R
R/util_gfft.R
R/util_verify.R
README.Rmd
README.md
vignettes/FFTrees_mytree.Rmd

This PR mostly expands the range of possible `my.tree` definitions (by increasing the contents of the global constant `directions_df`).  
- See an example in vignette on "Manually specifying FFTs" (`FFTrees_mytree.Rmd`).

Expand the range of interpretable `my.tree` definitions

---

R/FFTrees.R
R/fftrees_create.R
R/util_gfft.R

This PR 
1. prevents that goal and cost parameters are re-set when providing an existing `FFTrees` object to `FFTrees()` and 
2. fixes a bug:  Cue directions must not be flipped when applying `flip_exit()`, as FFT definitions — by convention — always predict TRUE/signal/1 (to the right).

Keeping goal and cost parameters of existing`FFTrees` object and fix a bug in `flip_exit()`

---

DESCRIPTION
R/plotFFTrees_function.R
R/printFFTrees_function.R
R/util_plot.R
README.Rmd
README.md
inst/CITATION
man/plot.FFTrees.Rd
vignettes/fft.bib
vignettes/guide.Rmd

- In `print(x)`:  Retrieve existing FFT description from object `x`, rather than using `inwords(x)` to re-create a verbal description.  
- else: Replacing local variables, adding doi to JDM reference and to Description.

Using existing description in `print(x, tree)`, plus minor maintenance

---

DESCRIPTION
R/util_gfft.R
R/util_verify.R
README.Rmd
README.md

This PR adds a new tree editing / trimming function `add_nodes()` and improves robustness by adding argument verification functions (e.g., for verifying the integrity of direction symbols and exit structures, as well as using both to verify fft definitions).

Tree trimming functions: Adding `add_nodes()`

---

DESCRIPTION
R/util_abc.R
R/util_const.R
R/util_gfft.R
R/util_verify.R
README.Rmd
README.md

This PR adds various utility functions (for verifying FFT variables and creating all subsets) to 
- create `all_node_subsets()` and 
- make `verify_fft_definition()` and `verify_fft_as_df()` stricter.

Adding `all_subsets()`, `all_node_subsets()` and improve verification functions

---

DESCRIPTION
NEWS.md
R/FFTrees.R
R/util_abc.R
R/util_gfft.R
R/util_verify.R
README.Rmd
README.md

This PR adds and revises an `all_fft_variants()` function (returning FFT definitions for all node subsets, all node orders, and all exit structures of a given FFT).

Add `all_fft_variants()` function

---

DESCRIPTION
R/util_gfft.R
README.Rmd
README.md

This PR adds a `quiet` argument to various tree trimming functions to hide/show feedback messages (plus some minor bug fixes).

Add `quiet` option to hide/show feedback messages

---

DESCRIPTION
NEWS.md
R/FFTrees.R
R/fftrees_apply.R
R/fftrees_create.R
R/fftrees_cuerank.R
R/fftrees_define.R
R/fftrees_ffttowords.R
R/fftrees_fitcomp.R
R/fftrees_grow_fan.R
R/fftrees_ranktrees.R
R/fftrees_wordstofftrees.R
R/util_color.R
R/util_const.R
R/util_gfft.R
README.Rmd
README.md

This PR mostly improves user feedback options (for tree trimming and general functions) by using different types of alert messages (from the **cli** package) and more specific logical parameters (e.g., `quiet.ini`, `quiet.fin` and `quiet.set`).
The functionality of `ufeed` (for _user feedback level_) is currently implemented as a global constants (see `util_const.R`).

Improve tree editing functions and user feedback

---

DESCRIPTION
R/fftrees_create.R
R/util_data.R
README.Rmd
README.md

This PR primarily fixes a bug in the previous one:  Rather than converting logical predictors with `NA` values to character or factors, the `NA` values in logical predictors are now treated by `addNA()` (i.e., creating a new factor level), just as it's done when handling character and factor predictors 
(plus some cosmetic changes to user feedback).

Bug fix: Treat `NA` values in logical like those in factors

---

DESCRIPTION
NEWS.md
R/FFTrees.R
R/fftrees_create.R
R/fftrees_grow_fan.R
R/util_const.R
R/util_data.R
man/FFTrees.Rd

This PR mostly fixes a bug in `fftrees_grow_fan()` that prevented the `ifan` algorithm from **stopping** when finding a **perfect**/**ideal** FFT (given the current `goal.chase` parameter). 
- Essentially, `grow_tree == FALSE` was set, but not being used before evaluating current stopping rule (e.g., computing `n_case_remaining` for `stopping.rule = "exemplars"`).
- In practice, this led to growing multi-node FFTs even though a subset was already perfect (given the current `goal.chase` parameter).
Also adding some user feedback, updating documentation, an noting that `stopping.rule = "statdelta"` is currently not implemented).

Bug fix:  Prevent `fftrees_grow_fan()` from overlooking perfect/ideal FFTs

---

DESCRIPTION
R/fftrees_cuerank.R
R/fftrees_grow_fan.R
R/fftrees_threshold_factor_grid.R
R/fftrees_threshold_numeric_grid.R
R/util_color.R
R/util_const.R
R/util_stats.R
README.Rmd
README.md

This PR fixes some bugs (due to implicit removal of `NA` values from the initial **cue evaluation** process) and adds more detailed options and user feedback messages (to handle and monitor what exactly is happening when there are `NA` values in numeric predictors).

Dealing with NA values in numeric predictors

---

DESCRIPTION
R/fftrees_apply.R
R/fftrees_cuerank.R
R/plotFFTrees_function.R
R/summaryFFTrees_function.R
R/util_data.R
R/util_stats.R
README.Rmd
README.md
man/fftrees_apply.Rd

This PR mostly explicates the handling of `NA` cases (and adds corresponding options and user feedback) when applying trees to data by `fftrees_apply()` (partially addressing some points currently discussed in Issue #160). 
Additionally, computations of `crit_br` (in plot and summary) now allow for `allow_NA_crit`.

Handle NA cases when applying trees to data

---

R/fftrees_apply.R
R/fftrees_fitcomp.R
R/fftrees_grow_fan.R
R/util_data.R
R/util_stats.R
man/classtable.Rd
man/comp_pred.Rd

This PR adds some handling of `NA` values in **competition** (primarily adding user feedback, but an error in RF is prevented by using `na.omit()` on training data), plus various minor improvements on user feedback on `NA` handling.

Handling NAs in competition

---

DESCRIPTION
R/util_stats.R
man/comp_pred.Rd

This PR fixes a bug that failed to remove `NA` values from training and test data when running the competition algorithms.
This handling of `NA`s for the competition models is only rudimentary (by removing all cases with missing values), but fixes the previous errors (which were caused by implicitly removing cases).

Removing NAs from competition algorithms

---

DESCRIPTION
R/FFTrees.R
R/fftrees_apply.R
R/fftrees_grow_fan.R
R/util_const.R
R/util_stats.R
README.Rmd
README.md
man/FFTrees.Rd

This PR adds `NA` counts (nr. of `NA` cue values and nr. of `NA` decision / indecisions) to each level
and enables (a rudimentary version of) `stopping.rule = "statdelta"` (currently stopping 1 level too late).

Add `NA` to level stats & enable `stopping.rule = "statdelta"`

---

DESCRIPTION
NEWS.md
R/FFTrees.R
R/fftrees_apply.R
R/fftrees_create.R
R/fftrees_grow_fan.R
R/summaryFFTrees_function.R
README.Rmd
README.md
man/FFTrees.Rd

This PR enables `stopping.rule = "statdelta"` even for `goal.chase = "cost"` (but the functionality remains experimental and somewhat dubious, as many stats seem to change in a non-monotonic fashion).  
+ corresponding updates of code comments and documentation

Enable stopping rule "statdelta"

---

DESCRIPTION
NEWS.md
R/plotFFTrees_function.R
README.md
man/plot.FFTrees.Rd

A user Guido Williams <guido.l.williams@gmail.com> emailed me asking for a grayscale option for plot.FFTrees().
>Dear Nathaniel,
>
>I have a question regarding the plot functions in the FFT package. Is there a simple way to print all plots/output in black and white/greyscale? For instance: plot(heart.fft, color = FALSE) or is there another way?
This would be very convenient for publication purposes.
This PR includes the new `grayscale` argument to `plot.FFTrees()` that enables this
See example below:
```
heart_fft <- FFTrees(formula = diagnosis ~.,
data = heart.train,
data.test = heart.test, 
decision.labels = c("Healthy", "Disease"))
plot(heart_fft, grayscale = TRUE)
```
Setting `grayscale = FALSE` (the default), gives us the color back
```
plot(heart_fft, grayscale = FALSE)
```

Allow grayscale option for plot.FFTrees()

---

DESCRIPTION
R/util_stats.R
man/classtable.Rd

Edited documentation of classtable() function to provide package anchor (using "\link[caret]{confusionMatrix}" syntax) to prevent current CRAN Note when checking cross-references.

Add pkg anchor when linking to external function in documentation
