ndphillips/FFTrees

tests/testthat/test-mytree.R
Test to ensure that #60 doesn't happen again
=> Test to ensure custom tree created in readme is interpreted correctly

DESCRIPTION, R/plotFFTrees_function.R, R/showcues_function.R, README.Rmd, README.md
Fixes 2 minor bugs in plots (grid lines in ROC plot of `plot.FFTrees()` and legend coordinates in `showcues()`) and revise some descriptive texts.
=> Fix 2 plotting bugs & revise descriptions

DESCRIPTION, NEWS.md, README.md, cran-comments.md, vignettes/FFTrees_plot.Rmd
Finalizing pkg for next CRAN release (scheduled for 2022-08-30).
=> Preparing CRAN release of version 1.7.0

DESCRIPTION, NEWS.md, README.md
A bunch of minor changes in preparation of the release of **FFTrees** version 1.7.0.
=> Minor changes for next CRAN release

DESCRIPTION, NEWS.md, R/plotFFTrees_function.R, README.md, man/plot.FFTrees.Rd, vignettes/FFTrees_plot.Rmd
=> Add additional sub-plotting options

DESCRIPTION, NEWS.md, R/fftrees_apply.R, R/plotFFTrees_function.R, README.md, inst/CITATION, man/plot.FFTrees.Rd
This PR contains minor improvements for plotting FFTs:
- enabled distinction between "decide" and "predict" in icon guide labels 
- passing some graphical parameters to text of panel titles.
=> Improved plotting

DESCRIPTION, NEWS.md, R/helper.R, README.md, inst/CITATION, man/comp_pred.Rd
As the present version fixes all bugs on my current list, let's push towards a CRAN release of **FFTrees** version 1.7.5.
=> Prepare for next CRAN release (FFTrees v1.7.5)

DESCRIPTION, README.Rmd, README.md
Minor edits (comments in README).
=> Minor maintenance

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_cuerank.R, R/fftrees_define.R, R/fftrees_ffttowords.R, R/fftrees_grow_fan.R, R/fftrees_wordstofftrees.R, R/helper.R, README.Rmd, README.md, man/FFTrees.Rd, man/fftrees_cuerank.Rd, man/fftrees_ffttowords.Rd, man/fftrees_wordstofftrees.Rd, vignettes/FFTrees_heart.Rmd, vignettes/FFTrees_mytree.Rmd
This PR merely wraps up some recent improvements:
- more consistent and explicit user feedback
- added documentation
- fixing minor bugs (e.g., in examples)
=> Mostly maintenance: User feedback, documentation, examples

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_apply.R, R/fftrees_ffttowords.R, R/helper.R, README.Rmd, README.md
Added a new `verify_all_cues_in_data()` helper function and using it when applying FFTrees (to partly address #111).
=> Verify that cues occur in data

DESCRIPTION, NEWS.md, README.Rmd, README.md, vignettes/FFTrees_accuracy_statistics.Rmd, vignettes/FFTrees_examples.Rmd, vignettes/FFTrees_function.Rmd, vignettes/FFTrees_heart.Rmd, vignettes/FFTrees_mytree.Rmd, vignettes/FFTrees_plot.Rmd, vignettes/guide.Rmd
Minor revision of vignettes (e.g., remark on 'train' vs. 'test' data for manually defined FFTs, names of links).
=> Minor revision

DESCRIPTION, NEWS.md, R/fftrees_cuerank.R, R/helper.R, R/inwords.R, R/plotFFTrees_function.R, R/printFFTrees_function.R, README.Rmd, README.md, vignettes/FFTrees_accuracy_statistics.Rmd, vignettes/FFTrees_examples.Rmd, vignettes/FFTrees_function.Rmd, vignettes/FFTrees_heart.Rmd, vignettes/FFTrees_mytree.Rmd, vignettes/FFTrees_plot.Rmd, vignettes/guide.Rmd
Mostly maintenance, e.g., 
- Added a `verify_tree()` helper function to be used in both plotting and printing FFTs.
- Minor revisions to increase robustness (interpreting inputs and providing user feedback).
- Unify chunk setups and figure sizes in README and vignettes.
=> Maintenance: Unify code, increase robustness, improve documentation

DESCRIPTION, NEWS.md, R/FFTreesdata_doc.R, R/helper_col.R, R/plotFFTrees_function.R, README.Rmd, README.md, inst/CITATION, man/mushrooms.Rd, man/plot.FFTrees.Rd
Getting ready for CRAN release of **FFTrees** v1.8.0.
=> Prepare CRAN release

NEWS.md, R/fftrees_cuerank.R, R/helper_col.R, R/zzz.R, README.Rmd, README.md, vignettes/FFTrees_examples.Rmd
Preparing for CRAN release of **FFTrees** version 1.8.0.
=> Prepare for CRAN release

DESCRIPTION, NEWS.md, vignettes/FFTrees_accuracy_statistics.Rmd, vignettes/FFTrees_examples.Rmd, vignettes/FFTrees_function.Rmd, vignettes/FFTrees_heart.Rmd, vignettes/FFTrees_mytree.Rmd, vignettes/FFTrees_plot.Rmd, vignettes/guide.Rmd
Maintenance of vignette contents:
- Hiding user feedback when creating FFTs
- Simplifying some titles and links
(Some redundancies — e.g. repeated explanations of `my.tree` — are to be addressed later.)
=> Updating vignettes

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_create.R, R/fftrees_cuerank.R, R/fftrees_grow_fan.R, R/fftrees_threshold_factor_grid.R, R/fftrees_threshold_numeric_grid.R, R/helper.R, R/helper_col.R, README.Rmd, README.md, inst/CITATION, man/fftrees_cuerank.Rd, vignettes/FFTrees_accuracy_statistics.Rmd, vignettes/FFTrees_examples.Rmd, vignettes/FFTrees_function.Rmd, vignettes/apa.csl, vignettes/fft.bib
This PR bundles various commits to chase minor bugs and improve robustness.  For instance, 
- add input verification checks (e.g., that criterion variable of `formula` occurs in `data`)
- improve user feedback (e.g., on current goals values)
- define permissible goals more clearly
- add support for re-using `"dprime"` as goal
Minor cleanup of code and vignettes (tbc).
=> Improve consistency and robustness

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_create.R, README.Rmd, README.md, inst/CITATION, man/FFTrees.Rd
This PR mainly adds some feedback messages on specific (and potentially problematic) combinations of `goal` and `cost` parameters (plus some tweaks to status badges in `README`).
=> Maintenance: Feedback on goal and cost settings

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_apply.R, R/fftrees_create.R, R/fftrees_grow_fan.R, R/helper.R, R/printFFTrees_function.R, README.Rmd, README.md, man/FFTrees.Rd, man/fftrees_create.Rd, tests/testthat/test-goal_cost.R, tests/testthat/test-specific_datasets.R
Re-arranging key argument lists (of `FFTrees()` and `fftrees_create()`) into more meaningful groups.
=> Maintenance: Re-arranging arguments of key functions

DESCRIPTION, R/FFTrees.R, R/fftrees_apply.R, R/fftrees_ffttowords.R, R/fftrees_wordstofftrees.R, R/util_abc.R, R/util_gfft.R, R/util_verify.R, README.Rmd, README.md
This PR adds various FFT verification and editing functions and renaming some variables (both arguments and functions).
=> Adding utility functions

DESCRIPTION, NEWS.md, R/fftrees_apply.R, R/fftrees_create.R, R/fftrees_grow_fan.R, R/util_abc.R, R/util_const.R, R/util_gfft.R, R/util_stats.R, README.Rmd, README.md, man/fftrees_apply.Rd, man/fftrees_create.Rd
This PR contains various maintenance commits, e.g.,
- increase the set of global constants (e.g., `valid_algorithm` and `default_goal`)
- store global constants as a separate file (`util_const.R`)
- update code comments and documentations.
=> Maintenance (e.g., global constants)

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_create.R, R/fftrees_cuerank.R, R/fftrees_threshold_factor_grid.R, R/fftrees_threshold_numeric_grid.R, README.Rmd, README.md, man/FFTrees.Rd, man/fftrees_create.Rd, man/fftrees_threshold_factor_grid.Rd, man/fftrees_threshold_numeric_grid.Rd
This PR enables users to maximize FFTs for a customized `my.goal` (defined by `my.goal.fun`) in the main `FFTrees()` function.
=> Enable `my.goal` and `my.goal.fun`

DESCRIPTION, R/fftrees_threshold_factor_grid.R, R/fftrees_threshold_numeric_grid.R, R/plotFFTrees_function.R, R/util_stats.R, README.Rmd, README.md, man/add_stats.Rd, man/classtable.Rd
Mostly maintenance:
- in `classtable()`: Improve user feedback for special cases in which `prediction_v` or `criterion_v` have no variance (short lengths)
- rename local variables (instances of `.` by `_`)
=> Maintenance and user feedback

DESCRIPTION, NEWS.md, README.Rmd, README.md, vignettes/fft.bib, vignettes/guide.Rmd
Final preparations for CRAN submission of **FFTrees** version 1.9.0.
=> Getting ready for CRAN submission

DESCRIPTION, NEWS.md, README.Rmd, README.md
Update and increment version (following CRAN release of **FFTrees** version 1.9.0, on 2023-02-08).
=> Update and increment version

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_wordstofftrees.R, R/printFFTrees_function.R, R/summaryFFTrees_function.R, R/util_abc.R, R/util_gfft.R, R/util_stats.R, man/FFTrees.Rd, man/add_stats.Rd, man/comp_pred.Rd, vignettes/FFTrees_mytree.Rmd
This PR improves the robustness when parsing FFTs from `my.tree` and adds detailed cost information when printing `FFTrees` objects (plus minor revisions of utility functions and improved documentation).
=> Improve parsing of `my.tree` and provide detailed cost info when printing FFTs

DESCRIPTION, R/util_gfft.R, README.Rmd, README.md
Add `drop_nodes()` to tree trimming functions (in `util_gfft.R`).
=> Add `drop_nodes()` to tree trimming functions

DESCRIPTION, R/fftrees_apply.R, R/fftrees_create.R, R/fftrees_ffttowords.R, R/fftrees_grow_fan.R, R/fftrees_wordstofftrees.R, R/predictFFTrees_function.R, R/util_abc.R, R/util_const.R, R/util_gfft.R, R/util_verify.R, README.Rmd, README.md, man/predict.FFTrees.Rd, tests/testthat/test-mytree.R
This PR adds an FFT trimming function `edit_nodes()` and a global `exit_types` constant.
=> Adding FFT trimming function and global constant

DESCRIPTION, R/FFTrees.R, R/fftrees_cuerank.R, R/fftrees_threshold_factor_grid.R, R/util_data.R, README.Rmd, README.md
This PR partially addresses #160 by changing `NA` values in character and factor predictors to `<NA>` levels.
Yet to add:  
- handle `NA` values in **numeric** predictors 
- handle `NA` values in **criterion** variable
=> Handle `NA` value in character and factor predictors

R/FFTrees.R, R/fftrees_apply.R, R/fftrees_create.R, R/fftrees_cuerank.R, R/fftrees_define.R, R/fftrees_ffttowords.R, R/fftrees_fitcomp.R, R/fftrees_grow_fan.R, R/fftrees_ranktrees.R, R/fftrees_wordstofftrees.R, R/predictFFTrees_function.R, R/showcues_function.R, R/util_abc.R, R/util_data.R, R/util_gfft.R, R/util_verify.R, man/FFTrees.Rd, man/showcues.Rd
This PR distinguishes 3 `quiet` aspects as 3 logical list elements `quiet = list(ini, fin, set)`.
=> More fine-grained user feedback options

R/fftrees_create.R, R/util_gfft.R
This PR only contains 2 minor improvements to user feedback messages.
=> User feedback messages (minor)

R/util_data.R, README.Rmd, README.md, vignettes/FFTrees_examples.Rmd
This PR identifies and reports `NA` cases (by data type and role) and converts logical predictors with `NA` cases into character predictors.
=> Identify & report NA cases & handle NA cases in character predictors

DESCRIPTION, NEWS.md, R/FFTrees.R, R/fftrees_create.R, R/fftrees_cuerank.R, R/util_data.R, R/util_verify.R, README.Rmd, README.md, man/fftrees_create.Rd
This PR moves many **initial data cleaning steps** into new utility functions (e.g., `verify_data_and_criterion()`, `clean_data()` and `handle_NA_data()`). This reduces clutter and improves consistency, by ensuring that the same steps are used for both training and test data (if applicable).
=> Make initial data cleaning more consistent

R/fftrees_apply.R, R/fftrees_grow_fan.R, R/util_data.R, R/util_stats.R
This PR only adds some monitoring and user feedback options, mostly for **sparse 2x2 matrices** (due to dropping NA values or handling decisions/predictions with zero variance).
To be continued (for applying corresponding FFTs...)
=> Maintenance: Monitoring NA cases and sparse 2x2 matrices

DESCRIPTION, R/fftrees_apply.R, R/util_const.R, R/util_gfft.R, README.Rmd, README.md
This PR classifies and counts decision outcomes for `NA` values in final nodes / terminal cues (in level stats).
=> Record decision outcomes for final `NA` cues

DESCRIPTION, R/fftrees_apply.R, R/fftrees_grow_fan.R, R/util_const.R, README.Rmd, README.md
This PR makes `debug` a global constant (and uses it for some detailed feedback settings).
=> Add debugging feedback

DESCRIPTION, NEWS.md, README.Rmd, README.md, vignettes/FFTrees_mytree.Rmd
Mostly revising the vignette `Manually specifying FFTs` to illustrate the new tree conversion and editing functions.
(to be continued)
=> Explaining tree conversion and trimming functions (by revising corresponding vignette)

DESCRIPTION, NEWS.md, R/fftrees_create.R, vignettes/FFTrees_mytree.Rmd
Continue revising vignette on _Manually specifying FFTs_ (to be finished).
=> Revising vignette on _Manually specifying FFTs_

DESCRIPTION, R/plotFFTrees_function.R, README.Rmd, README.md, man/plot.FFTrees.Rd, vignettes/FFTrees_heart.Rmd
Mostly deleting commented and unused content.
=> Revise vignettes and clean up code

DESCRIPTION, NEWS.md, R/util_const.R, README.Rmd, README.md, inst/CITATION
Only minor updates (just fiddling with some settings).
=> Minor changes

DESCRIPTION, NEWS.md, R/FFTrees.R, README.Rmd, README.md, man/FFTrees.Rd
Minor changes, mostly adding @alias FFTrees-package to `FFTrees()` (in response to <https://github.com/r-lib/roxygen2/issues/1491>).
=> Package maintenance

R/fftrees_apply.R
involving handling of NA values
=> Minor tweaks

README.Rmd, README.md
Provide a table with links to various package **Resources** on README and derived online documentation (to finalize #216).
=> Add resources to README

DESCRIPTION, tests/testthat/test_09_cost.R, tests/testthat/test_10_tree_definitions.R, tests/testthat/test_11_NA_data.R, vignettes/FFTrees_examples.Rmd, vignettes/FFTrees_mytree.Rmd
Testing the extraction, editing, gathering, and using tree definitions (and address #227).
=> Tests for editing and using tree.definitions

NEWS.md, R/plotFFTrees_function.R, R/util_plot.R
Bug fixes for labeling FFT (in `main` title and row labels of 2x2 matrix for `test` data).
=> Fix minor bugs in plotting

R/FFTreesdata_doc.R, R/plotFFTrees_function.R, docs/reference/heartdisease.html, inst/WORDLIST, man/heartdisease.Rd
Adding options and cosmetic tweaks (e.g., for plot labels) and details in data documentation (on `heartdisease` data).
=> Various cosmetic tweaks
